name: Dynamic Message

on: push

jobs:
  print-Message:
    runs-on: ubuntu-latest

    steps:
      - name: Print Details
        run: |
          echo "Hello ${{ github.actor }}"
          echo "You pushed to ${{ github.ref_name }}"
          echo "from repository ${{ github.event.repository.name }}"
          echo "at $(TZ='Asia/Kolkata' date '+%Y-%m-%d %H:%M IST')"